### ISSUE TITLE
ROS 2 Beta 2 package list

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosdistro-testing#2]
Built using ament's topological list of all packages in ros2.repos and turtlebot2_demo.repos.

Combined with the current status of the package on the ROS 2 test farm. @ros2/team, if there's something you see on this list that isn't necessary for a release, please please please let me know so I don't spend time packaging it :grin:. Likewise if there's anything you know we'll need please link me to the source repo so I can add it to my heterogenous test workspace (and eventually package it).

Things that I know I can skip are currently marked as `skipping`. Otherwise things are either `stable`, in that the package builds without incident, `forked` which means I had to fork and modify the package in order to release it (generally dependency related) and will be submitting PRs to upstream those changes, `pending` which means it's been released but hasn't had its first build yet, or `unreleased` which means I haven't gotten to it or am waiting on a dependency of it.

Moving the table to a comment so I can parse it easier.

**Progress according to [this script](https://gist.github.com/nuclearsandwich/8b937db4188ed54304f6f3293a19f757#file-packageprogress-sh)**

155 packages currently stable and 0 pending. Great work!
Check out package statuses on the farm at http://repo.ros2.org/status_page/
### blocked repositories
0 packages currently blocked

### broken repositories
5 packages currently broken
- ros2/examples
- ros2/ros1_bridge

### merged repositories
0 packages currently merged

### forked repositories
1 packages currently forked
- vendor/console_bridge

### outdated repositories
0 packages currently outdated

### unreleased repositories
0 packages currently unreleased

**Comment by clalancette** [comment]
Packages that are important for the turtlebot demo:

- astra_camera (in the list above)
- ceres-solver (in the list above)
- cartographer (in the list above)
- cartographer_ros (in the list above)
- cartographer_ros_msgs (in the list above)
- depthimage_to_laserscan (https://github.com/ros2/depthimage_to_laserscan)
- image_geometry (in the list above)
- joy (https://github.com/ros2/joystick_drivers , but the code is still a WIP and won't build right now)
- launch (in the list above)
- nav_msgs (in the list above)
- pcl_conversions (in the list above)
- ros1_bridge (in the list above)
- sensor_msgs (in the list above)
- std_msgs (in the list above)
- teleop_twist_joy (in the list above)
- tf2_msgs (in the list above)
- tf2_ros (in the list above)
- turtlebot2_drivers (in the list above)

**Comment by dirk-thomas** [comment]
The packages in the repo https://github.com/ros2/cli_tools will likely be replaced with the packages (to be placed) in https://github.com/ros2/ros2cli.

**Comment by dirk-thomas** [comment]
The following packages would be obsolete if we would switch to use `flake8` where the other are being used:
* ament_pep8
* ament_pep257
* ament_pyflakes
  * and the corresponding CMake packages

**Comment by nuclearsandwich** [comment]
> joy (https://github.com/ros2/joystick_drivers , but the code is still a WIP and won't build right now)

So the from scratch driver in the current turtlebot2 repos file should get unshipped? https://github.com/ros2/joystick_drivers_from_scratch

**Comment by mikaelarguedas** [comment]
yep hopefully I'll get back to this this afternoon and will be able to update the repos file to use https://github.com/ros2/joystick_drivers and remove / unship https://github.com/ros2/joystick_drivers_from_scratch

**Comment by nuclearsandwich** [comment]
I just yanked python_orocos_kdl since the build was failing (which may point to configuration issues with the orocos_kdl package, to be investigated) and it has an AMENT_IGNORE file. However, tf2_geometry_msgs depends on python_orocos_kdl. Is this an optional dependency / build ordering dependency that I can patch out for the release or do I need to get python_orocos_kdl working and add it back in?

**Comment by dhood** [comment]
Yeah, the `python_orocos_kdl` dependency isn't currently used for `tf2_geometry_msgs`: https://github.com/ros2/geometry2/pull/21

**Comment by nuclearsandwich** [comment]
The ROS 1 bridge needs to be built from source in order to properly detect available ROS 1 messages correct?

**Comment by dirk-thomas** [comment]
> The ROS 1 bridge needs to be built from source in order to properly detect available ROS 1 messages correct?

Yes, but we could provide a binary package which is built against a "common set" of ROS 1 packages.

**Comment by nuclearsandwich** [comment]
> Yes, but we could provide a binary package which is built against a "common set" of ROS 1 packages.

In order to do so, would we need to depend on lunar or kinetic packages?

**Comment by dirk-thomas** [comment]
> > Yes, but we could provide a binary package which is built against a "common set" of ROS 1 packages.

> In order to do so, would we need to depend on lunar or kinetic packages?

Either would be fine. I would favor `kinetic` since it is a LTS release.

**Comment by nuclearsandwich** [comment]
| package                                | repo                                                     | status   | note                                                                                                |
|----------------------------------------|----------------------------------------------------------|----------|-----------------------------------------------------------------------------------------------------|
| ament_cppcheck                         | ament/ament_lint/ament_cppcheck                          | stable   |                                                                                                     |
| ament_flake8                           | ament/ament_lint/ament_flake8                            | stable   |                                                                                                     |
| ament_package                          | ament/ament_package                                      | stable   |                                                                                                     |
| ament_cmake_core                       | ament/ament_cmake/ament_cmake_core                       | stable   |                                                                                                     |
| ament_cmake_export_definitions         | ament/ament_cmake/ament_cmake_export_definitions         | stable   |                                                                                                     |
| ament_cmake_export_dependencies        | ament/ament_cmake/ament_cmake_export_dependencies        | stable   |                                                                                                     |
| ament_cmake_export_include_directories | ament/ament_cmake/ament_cmake_export_include_directories | stable   |                                                                                                     |
| ament_cmake_export_interfaces          | ament/ament_cmake/ament_cmake_export_interfaces          | stable   |                                                                                                     |
| ament_cmake_export_libraries           | ament/ament_cmake/ament_cmake_export_libraries           | stable   |                                                                                                     |
| ament_cmake_export_link_flags          | ament/ament_cmake/ament_cmake_export_link_flags          | stable   |                                                                                                     |
| ament_cmake_gmock                      | ament/ament_cmake/ament_cmake_gmock                      | stable   |                                                                                                     |
| ament_cmake_gtest                      | ament/ament_cmake/ament_cmake_gtest                      | stable   |                                                                                                     |
| ament_cmake_include_directories        | ament/ament_cmake/ament_cmake_include_directories        | stable   |                                                                                                     |
| ament_cmake_libraries                  | ament/ament_cmake/ament_cmake_libraries                  | stable   |                                                                                                     |
| ament_cmake                            | ament/ament_cmake/ament_cmake                            | stable   |                                                                                                     |
| ament_cmake_nose                       | ament/ament_cmake/ament_cmake_nose                       | stable   |                                                                                                     |
| ament_cmake_python                     | ament/ament_cmake/ament_cmake_python                     | stable   |                                                                                                     |
| ament_cmake_target_dependencies        | ament/ament_cmake/ament_cmake_target_dependencies        | stable   |                                                                                                     |
| ament_cmake_test                       | ament/ament_cmake/ament_cmake_test                       | stable   |                                                                                                     |
| ament_cmake_auto                       | ament/ament_cmake/ament_cmake_auto                       | stable   |                                                                                                     |
| ament_lint_auto                        | ament/ament_lint/ament_lint_auto                         | stable   |                                                                                                     |
| ament_pep8                             | ament/ament_lint/ament_pep8                              | stable   |                                                                                                     |
| ament_pep257                           | ament/ament_lint/ament_pep257                            | stable   |                                                                                                     |
| ament_pyflakes                         | ament/ament_lint/ament_pyflakes                          | stable   |                                                                                                     |
| ament_copyright                        | ament/ament_lint/ament_copyright                         | stable   |                                                                                                     |
| ament_clang_format                     | ament/ament_lint/ament_clang_format                      | stable   |                                                                                                     |
| ament_cpplint                          | ament/ament_lint/ament_cpplint                           | stable   |                                                                                                     |
| ament_index_python                     | ament/ament_index/ament_index_python                     | stable   |                                                                                                     |
| ament_lint_cmake                       | ament/ament_lint/ament_lint_cmake                        | stable   |                                                                                                     |
| ament_cmake_lint_cmake                 | ament/ament_lint/ament_cmake_lint_cmake                  | stable   |                                                                                                     |
| ament_cmake_copyright                  | ament/ament_lint/ament_cmake_copyright                   | stable   |                                                                                                     |
| ament_cmake_clang_format               | ament/ament_lint/ament_cmake_clang_format                | stable   |                                                                                                     |
| ament_cmake_cppcheck                   | ament/ament_lint/ament_cmake_cppcheck                    | stable   |                                                                                                     |
| ament_cmake_cpplint                    | ament/ament_lint/ament_cmake_cpplint                     | stable   |                                                                                                     |
| ament_cmake_flake8                     | ament/ament_lint/ament_cmake_flake8                      | stable   |                                                                                                     |
| ament_cmake_pep257                     | ament/ament_lint/ament_cmake_pep257                      | stable   |                                                                                                     |
| ament_cmake_pep8                       | ament/ament_lint/ament_cmake_pep8                        | stable   |                                                                                                     |
| ament_cmake_pyflakes                   | ament/ament_lint/ament_cmake_pyflakes                    | stable   |                                                                                                     |
| ament_cmake_uncrustify                 | ament/ament_lint/ament_cmake_uncrustify                  | stable   |                                                                                                     |
| ament_python                           | ament/ament_python                                       | stable   |                                                                                                     |
| ceres_solver                           | vendor/ceres-solver                                      | stable   |                                                                                                     |
| cartographer                           | vendor/cartographer                                      | stable   |                                                                                                     |
| console_bridge                         | vendor/console_bridge                                    | forked   | https://github.com/ros2/ros2/pull/373                                                               |
| fastcdr                                | eProsima/Fast-CDR                                        | stable   |                                                                                                     |
| fastrtps                               | eProsima/Fast-RTPS                                       | stable   | may release against 1.5.0 patched                                                                   |
| gmock_vendor                           | ament/gmock_vendor                                       | stable   |                                                                                                     |
| gtest_vendor                           | ament/gtest_vendor                                       | stable   |                                                                                                     |
| launch                                 | ros2/launch/launch                                       | stable   |                                                                                                     |
| launch_testing                         | ros2/launch/launch_testing                               | stable   |                                                                                                     |
| orocos_kdl                             | ros2/orocos_kinematics_dynamics/orocos_kdl               | stable   |                                                                                                     |
| osrf_pycommon                          | ament/osrf_pycommon                                      | stable   |                                                                                                     |
| ament_tools                            | ament/ament_tools                                        | stable   |                                                                                                     |
| poco_vendor                            | ros2/poco_vendor                                         | stable   |                                                                                                     |
| class_loader                           | ros/class_loader                                         | stable   |                                                                                                     |
| tinyxml_vendor                         | ros2/tinyxml_vendor                                      | stable   |                                                                                                     |
| uncrustify                             | ament/uncrustify                                         | stable   |                                                                                                     |
| ament_uncrustify                       | ament/ament_lint/ament_uncrustify                        | stable   |                                                                                                     |
| ament_lint_common                      | ament/ament_lint/ament_lint_common                       | stable   |                                                                                                     |
| ament_cmake_ros                        | ros2/ament_cmake_ros/ament_cmake_ros                     | stable   |                                                                                                     |
| ament_index_cpp                        | ament/ament_index/ament_index_cpp                        | stable   |                                                                                                     |
| connext_cmake_module                   | ros2/rmw_connext/connext_cmake_module                    | skipping | only packaging Fast-RTPS support                                                                    |
| dummy_robot_bringup                    | ros2/demos/dummy_robot/dummy_robot_bringup               | stable   |                                                                                                     |
| fastrtps_cmake_module                  | ros2/rmw_fastrtps/fastrtps_cmake_module                  | stable   |                                                                                                     |
| opensplice_cmake_module                | ros2/rmw_opensplice/opensplice_cmake_module              | skipping | only packaging Fast-RTPS support                                                                    |
| python_cmake_module                    | ros2/rosidl/python_cmake_module                          | stable   |                                                                                                     |
| rcutils                                | ros2/rcutils                                             | stable   |                                                                                                     |
| rmw                                    | ros2/rmw/rmw                                             | stable   |                                                                                                     |
| rmw_implementation_cmake               | ros2/rmw/rmw_implementation_cmake                        | stable   |                                                                                                     |
| rosidl_default_generators              | ros2/rosidl_typesupport/rosidl_default_generators        | stable   |                                                                                                     |
| rosidl_default_runtime                 | ros2/rosidl_typesupport/rosidl_default_runtime           | stable   |                                                                                                     |
| rosidl_generator_dds_idl               | ros2/rosidl_dds/rosidl_generator_dds_idl                 | stable   |                                                                                                     |
| rosidl_parser                          | ros2/rosidl/rosidl_parser                                | stable   |                                                                                                     |
| rosidl_cmake                           | ros2/rosidl/rosidl_cmake                                 | stable   |                                                                                                     |
| rosidl_typesupport_interface           | ros2/rosidl/rosidl_typesupport_interface                 | stable   |                                                                                                     |
| rosidl_generator_c                     | ros2/rosidl/rosidl_generator_c                           | stable   |                                                                                                     |
| rmw_connext_shared_cpp                 | ros2/rmw_connext/rmw_connext_shared_cpp                  | skipping | only packaging Fast-RTPS support                                                                    |
| rosidl_generator_cpp                   | ros2/rosidl/rosidl_generator_cpp                         | stable   |                                                                                                     |
| rosidl_typesupport_c                   | ros2/rosidl_typesupport/rosidl_typesupport_c             | stable   |                                                                                                     |
| rosidl_typesupport_connext_cpp         | ros2/rmw_connext/rosidl_typesupport_connext_cpp          | skipping | only packaging Fast-RTPS support                                                                    |
| rosidl_typesupport_connext_c           | ros2/rmw_connext/rosidl_typesupport_connext_c            | skipping | only packaging Fast-RTPS support                                                                    |
| rmw_connext_cpp                        | ros2/rmw_connext/rmw_connext_cpp                         | skipping | only packaging Fast-RTPS support                                                                    |
| rosidl_typesupport_cpp                 | ros2/rosidl_typesupport/rosidl_typesupport_cpp           | stable   |                                                                                                     |
| rosidl_typesupport_introspection_c     | ros2/rosidl/rosidl_typesupport_introspection_c           | stable   |                                                                                                     |
| rosidl_typesupport_introspection_cpp   | ros2/rosidl/rosidl_typesupport_introspection_cpp         | stable   |                                                                                                     |
| rmw_fastrtps_cpp                       | ros2/rmw_fastrtps/rmw_fastrtps_cpp                       | stable   |                                                                                                     |
| rosidl_typesupport_opensplice_cpp      | ros2/rmw_opensplice/rosidl_typesupport_opensplice_cpp    | skipping | only packaging Fast-RTPS support                                                                    |
| rosidl_typesupport_opensplice_c        | ros2/rmw_opensplice/rosidl_typesupport_opensplice_c      | skipping | only packaging Fast-RTPS support                                                                    |
| rmw_opensplice_cpp                     | ros2/rmw_opensplice/rmw_opensplice_cpp                   | skipping | only packaging Fast-RTPS support                                                                    |
| rmw_implementation                     | ros2/rmw_implementation/rmw_implementation               | stable   |                                                                                                     |
| rosidl_generator_py                    | ros2/rosidl/rosidl_generator_py                          | stable   |                                                                                                     |
| builtin_interfaces                     | ros2/common_interfaces/builtin_interfaces                | stable   |                                                                                                     |
| example_interfaces                     | ros2/example_interfaces                                  | stable   |                                                                                                     |
| lifecycle_msgs                         | ros2/rcl_interfaces/lifecycle_msgs                       | stable   |                                                                                                     |
| pendulum_msgs                          | ros2/demos/pendulum_msgs                                 | stable   |                                                                                                     |
| rcl_interfaces                         | ros2/rcl_interfaces/rcl_interfaces                       | stable   |                                                                                                     |
| rttest                                 | ros2/realtime_support/rttest                             | stable   |                                                                                                     |
| std_msgs                               | ros2/common_interfaces/std_msgs                          | stable   |                                                                                                     |
| actionlib_msgs                         | ros2/common_interfaces/actionlib_msgs                    | stable   |                                                                                                     |
| geometry_msgs                          | ros2/common_interfaces/geometry_msgs                     | stable   |                                                                                                     |
| cartographer_ros_msgs                  | ros2/cartographer_ros/cartographer_ros_msgs              | stable   |                                                                                                     |
| diagnostic_msgs                        | ros2/common_interfaces/diagnostic_msgs                   | stable   |                                                                                                     |
| nav_msgs                               | ros2/common_interfaces/nav_msgs                          | stable   |                                                                                                     |
| rcl                                    | ros2/rcl/rcl                                             | stable   |                                                                                                     |
| rcl_lifecycle                          | ros2/rcl/rcl_lifecycle                                   | stable   |                                                                                                     |
| rclcpp                                 | ros2/rclcpp/rclcpp                                       | stable   |                                                                                                     |
| composition                            | ros2/demos/composition                                   | stable   |                                                                                                     |
| dummy_map_server                       | ros2/demos/dummy_robot/dummy_map_server                  | stable   |                                                                                                     |
| examples_rclcpp_minimal_client         | ros2/examples/rclcpp/minimal_client                      | stable   |                                                                                                     |
| examples_rclcpp_minimal_composition    | ros2/examples/rclcpp/minimal_composition                 | stable   |                                                                                                     |
| examples_rclcpp_minimal_publisher      | ros2/examples/rclcpp/minimal_publisher                   | stable   |                                                                                                     |
| examples_rclcpp_minimal_service        | ros2/examples/rclcpp/minimal_service                     | stable   |                                                                                                     |
| examples_rclcpp_minimal_subscriber     | ros2/examples/rclcpp/minimal_subscriber                  | stable   |                                                                                                     |
| examples_rclcpp_minimal_timer          | ros2/examples/rclcpp/minimal_timer                       | stable   |                                                                                                     |
| rclpy                                  | ros2/rclpy/rclpy                                         | stable   |                                                                                                     |
| demo_nodes_py                          | ros2/demos/demo_nodes_py                                 | stable   |                                                                                                     |
| examples_rclpy_minimal_client          | ros2/examples/rclpy/services/minimal_client              | broken   | https://github.com/ros2/rosdistro/issues/7                                                          |
| examples_rclpy_minimal_publisher       | ros2/examples/rclpy/topics/minimal_publisher             | broken   | https://github.com/ros2/rosdistro/issues/7                                                          |
| examples_rclpy_minimal_service         | ros2/examples/rclpy/services/minimal_service             | broken   | https://github.com/ros2/rosdistro/issues/7                                                          |
| examples_rclpy_minimal_subscriber      | ros2/examples/rclpy/topics/minimal_subscriber            | broken   | https://github.com/ros2/rosdistro/issues/7                                                          |
| rclcpp_lifecycle                       | ros2/rclcpp/rclcpp_lifecycle                             | stable   |                                                                                                     |
| lifecycle                              | ros2/demos/lifecycle                                     | stable   |                                                                                                     |
| ros2cli                                | ros2/ros2cli/ros2cli                                     | stable   |                                                                                                     |
| ros2msg                                | ros2/ros2cli/ros2msg                                     | stable   |                                                                                                     |
| ros2node                               | ros2/ros2cli/ros2node                                    | stable   |                                                                                                     |
| ros2pkg                                | ros2/ros2cli/ros2pkg                                     | stable   |                                                                                                     |
| ros2run                                | ros2/ros2cli/ros2run                                     | stable   |                                                                                                     |
| ros2service                            | ros2/ros2cli/ros2service                                 | stable   |                                                                                                     |
| ros2srv                                | ros2/ros2cli/ros2srv                                     | stable   |                                                                                                     |
| sensor_msgs                            | ros2/common_interfaces/sensor_msgs                       | stable   |                                                                                                     |
| astra_camera                           | ros2/ros_astra_camera                                    | stable   |                                                                                                     |
| demo_nodes_cpp                         | ros2/demos/demo_nodes_cpp                                | stable   |                                                                                                     |
| dummy_sensors                          | ros2/demos/dummy_robot/dummy_sensors                     | stable   |                                                                                                     |
| image_geometry                         | ros2/vision_opencv/image_geometry                        | stable   |                                                                                                     |
| depth_to_pointcloud                    | ros2/turtlebot2_demo/depth_to_pointcloud                 | stable   |                                                                                                     |
| depthimage_to_laserscan                | ros2/depthimage_to_laserscan                             | stable   |                                                                                                     |
| image_tools                            | ros2/demos/image_tools                                   | stable   |                                                                                                     |
| intra_process_demo                     | ros2/demos/intra_process_demo                            | stable   |                                                                                                     |
| joy                                    | ros2/joystick_drivers/joy                                | stable   |                                                                                                     |
| pcl_conversions                        | ros2/pcl_conversions                                     | stable   |                                                                                                     |
| ros1_bridge                            | ros2/ros1_bridge                                         | broken   | tests don't build. Investigating building without tests https://github.com/ros2/rosdistro/issues/8  |
| shape_msgs                             | ros2/common_interfaces/shape_msgs                        | stable   |                                                                                                     |
| sros2                                  | ros2/sros2                                               | stable   |                                                                                                     |
| std_srvs                               | ros2/common_interfaces/std_srvs                          | stable   |                                                                                                     |
| stereo_msgs                            | ros2/common_interfaces/stereo_msgs                       | stable   |                                                                                                     |
| teleop_twist_joy                       | ros2/teleop_twist_joy                                    | stable   |                                                                                                     |
| teleop_twist_keyboard                  | ros2/teleop_twist_keyboard                               | stable   |                                                                                                     |
| test_communication                     | ros2/system_tests/test_communication                     | stable   |                                                                                                     |
| ros2topic                              | ros2/ros2cli/ros2topic                                   | stable   |                                                                                                     |
| test_rclcpp                            | ros2/system_tests/test_rclcpp                            | stable   |                                                                                                     |
| tf2                                    | ros2/geometry2/tf2                                       | stable   |                                                                                                     |
| map_server                             | ros2/navigation/map_server                               | stable   |                                                                                                     |
| tf2_msgs                               | ros2/geometry2/tf2_msgs                                  | stable   |                                                                                                     |
| tf2_ros                                | ros2/geometry2/tf2_ros                                   | stable   |                                                                                                     |
| tf2_eigen                              | ros2/geometry2/tf2_eigen                                 | stable   |                                                                                                     |
| tf2_geometry_msgs                      | ros2/geometry2/tf2_geometry_msgs                         | stable   |                                                                                                     |
| amcl                                   | ros2/navigation/amcl                                     | stable   |                                                                                                     |
| tlsf                                   | ros2/tlsf/tlsf                                           | stable   |                                                                                                     |
| tlsf_cpp                               | ros2/realtime_support/tlsf_cpp                           | stable   |                                                                                                     |
| pendulum_control                       | ros2/demos/pendulum_control                              | stable   |                                                                                                     |
| topic_monitor                          | ros2/demos/topic_monitor                                 | stable   |                                                                                                     |
| trajectory_msgs                        | ros2/common_interfaces/trajectory_msgs                   | stable   |                                                                                                     |
| turtlebot2_follower                    | ros2/turtlebot2_demo/turtlebot2_follower                 | stable   |                                                                                                     |
| urdfdom_headers                        | ros2/urdfdom_headers                                     | stable   |                                                                                                     |
| cartographer_ros                       | ros2/cartographer_ros/cartographer_ros                   | stable   |                                                                                                     |
| turtlebot2_drivers                     | ros2/turtlebot2_demo/turtlebot2_drivers                  | stable   |                                                                                                     |
| urdfdom                                | ros2/urdfdom                                             | stable   |                                                                                                     |
| urdf                                   | ros2/robot_model/urdf                                    | stable   |                                                                                                     |
| kdl_parser                             | ros2/robot_model/kdl_parser                              | stable   |                                                                                                     |
| robot_state_publisher                  | ros2/robot_state_publisher                               | stable   |                                                                                                     |
| visualization_msgs                     | ros2/common_interfaces/visualization_msgs                | stable   |                                                                                                     |

**Comment by nuclearsandwich** [comment]
Updated the package list and statuses from the latest ros2.repos and turtlebot2_demo.repos. Unless you see a package listed there without a status of `skipping`, it's not in my list of things to package.

**Comment by nuclearsandwich** [comment]
ros2/realtime_support and ros2/demos are blocked by conflicting version numbers in realtime_support. (0.0.0 vs 0.0.1). Even creating separate tracks and ignoring the other package doesn't satisfy bloom currently as the package versions are checked before the ignores are observed.

**Comment by nuclearsandwich** [comment]
With the exception of packages with outstanding python dependency issues. I've updated every package release on the farm so whatever's built by tomorrow we'll have for testing.

**Comment by mikaelarguedas** [comment]
@nuclearsandwich I don't know if it can spare you some time but I don't think that we need to release packages that don't install anything (mostly test packages)

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich I don't know if it can spare you some time but I don't think that we need to release packages that don't install anything (mostly test packages)

Can you point out which packages those would be? The most important thing to cut down on is arm64 build time.

**Comment by mikaelarguedas** [comment]
hmm that would be the system_tests repo. oh wait, actually given that https://github.com/ros2/system_tests/issues/191 never happened it would be only test_rclcpp... so not a big win, getting rid of test_communication would have saved more time because many messages to generate.

**Comment by dirk-thomas** [comment]
That is another good reason why we should just do ros2/system_tests#191.

**Comment by nuclearsandwich** [comment]
The release is out, the available packages are listed for [amd64](http://repo.ros2.org/status_page/ros_r2b2_default.html) and [arm64](http://repo.ros2.org/status_page/ros_r2b2_uxv8.html).
