### ISSUE TITLE
Cannot locate rosdep definition for [cmake_modules]

### ISSUE THREAD

**Issue by jacobperron** [ros2/rosdistro-testing#285]
[geometry2](https://github.com/ros2/geometry2) depends on [cmake_modules](https://github.com/ros/cmake_modules).

Steps to reproduce:

    wget https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
    vcs import --repos < ros2.repos src
    rosdep update
    rosdep install --from-paths src --ignore-src --rosdistro bouncy -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 rti-connext-dds-5.3.1 urdfdom_headers"

Error:

    ERROR: the following packages/stacks could not have their rosdep keys resolved
    to system dependencies:
    tf2_sensor_msgs: Cannot locate rosdep definition for [cmake_modules]

I'm not sure why this is just happening now, perhaps it had something to do with ros2/geometry2#75 ?

**Comment by dirk-thomas** [comment]
`cmake_modules` is not released in any ROS 2 distro so `rosdep` won't be able to resolve it.

**Comment by wjwwood** [comment]
I'd rather not see `cmake_modules` go forward into ROS 2. I don't know why it is being used, but if it's for eigen, then I'd prefer to see an `eigen_cmake_module` package created for this purpose instead.

**Comment by nuclearsandwich** [comment]
@jacobperron did you get what you needed resolved for this?

**Comment by jacobperron** [comment]
> @jacobperron did you get what you needed resolved for this?

@nuclearsandwich This error still exists and I expect will affect users following the instructions for installing from source. I guess tf2_sensor_msgs should be updated to remove the dependency to `cmake_modules`, if possible, or as @wjwwood suggests, replace the dependency with an `eigen_cmake_module` package.

**Comment by nuclearsandwich** [comment]
Ah I didn't see that this was a recently un-ignored package and so wasn't part of previous releases. I am unfamiliar with the cmake_modules package but it seems that at least Eigen 3 provides its own cmake modules upstream and other ROS 2 packages appear to use them directly and that looks like what the tf2_sensor_msgs package is doing for ROS 2.

Given that CI is running for tf2_sensor_msgs appears to be running successfully and that dependency key is not satisfied by anything on the CI machine nor in the colcon workspace it is likely vestigial.
