### ISSUE TITLE
Package naming issues with urdfdom-headers.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosdistro-testing#6]
The crucial issue is that we need urdfdom-headers master in xenial, which provides urdfdom-headers 0.4.

At the moment, we need a particular fork of urdfdom-headers master: https://github.com/ros2/urdfdom_headers, at least until https://github.com/ros/urdfdom_headers/pull/34

This fork was packaged on the ROS 2 buildfarm as urdfdom_headers and released, but some packages specified `urdfdom-headers` (note dash) rather than the underscored package name. When submitting a PR to standardize on `urdfdom_headers` (note underscore) I received [feedback that package names now allow the package to use the dashed name](https://github.com/ros2/robot_model/pull/1#discussion_r122772603) and I should change the ROS 2 package name to use the dash rather than changing these rosdep keys.

I updated [my release](https://github.com/nuclearsandwich/urdfdom-headers-release/blob/1bae4d2f831ad001e0cea0067284b6508770c8a6/r2b2/package.xml) package name and [opened](https://github.com/ros2/urdfdom/pull/3) [pull](https://github.com/ros2/robot_state_publisher/pull/4) [requests](https://github.com/ros2/cartographer_ros/pull/6) as well as updated https://github.com/ros2/robot_model/pull/1 to use the dashed name.

 https://github.com/ros2/urdfdom/pull/3 caused CI to start failing and was later reverted.

By changing the dependency key from `urdfdom_headers` to `urdfdom-headers` and changing the `urdfdom_headers` package name to `urdfdom-headers` only in the [release-provided package.xml](https://github.com/nuclearsandwich/urdfdom-headers-release/blob/1bae4d2f831ad001e0cea0067284b6508770c8a6/r2b2/package.xml) ament could not correctly insure that the cmake package `urdfdom_headers` needed to be built before `urdfdom`.

I tested some permanent fixes locally. Bringing the release package.xml into the source directory causes ament to raise an InvalidPackage exception due to the dashed name.

Omitting the package.xml and trying to change the cmake project name causes ament to be unable to find the package because it no longer satisfies [this regexp](https://github.com/ament/ament_tools/blob/711fa60ffaa711d5d4f26ea5bcef6e794bfd9cae/ament_tools/package_types/cmake.py#L83).

I'm not sure what the best thing to do is. The least creative would seem to be to return to the original plan of changing the urdfdom-headers downstream packages to depend on urdfdom_headers (note underscore) with a comment that this dependency should be updated when the system urdfdom-headers is suitable.

**Comment by nuclearsandwich** [comment]
@dirk-thomas per today's meeting the preferred way forward is to update ament_tools and ament_package to accept `-` in package names and then proceed with standardizing on `urdfdom-headers` in ROS 2 package dependencies.

While trying to find the REP change that allows this I found the PR https://github.com/ros-infrastructure/rep/pull/126 but as far as I can tell no like change has been made for REP 140. Is there a need to update REP 140 before making the changes in ament or should both happen in parallel. I understand the technical difference between the naming change in REPs 1{27,40} and REP 144, is a change to 144 also required even if it is only a clarification of when the dash should or must not be used?

**Comment by mikaelarguedas** [comment]
@nuclearsandwich I think that https://github.com/ros-infrastructure/rep/pull/126 modified both REP127 and REP140 to allow dashes. Not being very famililar with the REP system the following statement is purely subjective, it looks to me that it would be sensible to update REP144 accordingly.

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich I think that https://github.com/ros-infrastructure/rep/pull/126 modified both REP127 and REP140 to allow dashes. Not being very famililar with the REP system the following statement is purely subjective, it looks to me that it would be sensible to update REP144 accordingly.

ah yes. Clearly been staring at screens too long lately. It was only REP 144 I couldn't find mention of the change in package naming. Which may be intentional because ROS packages should still not contain dashes (but package format specifications may allow them for the special case defined)

**Comment by dirk-thomas** [comment]
REP 144 is only in draft state and the work seems to be suspended (see ros-infrastructure/rep#96) therefore I don't think it needs to be considered.

The following issue in the `catkin_pkg` repo contains the feature request: ros-infrastructure/catkin_pkg#161 The ticket references the PR which got merged to relax the naming conventions.

**Comment by nuclearsandwich** [comment]
Once ament_package accepts dashes, we still have to resolve finding the urdfdom-headers package during source builds.

We could either drop the dash-named release package.xml file in the source repo, or change the cmake project to use a dashed name. Of the two, I prefer putting a package.xml in the source repo. Otherwise we'd be dealing with source/build level package name inconsistencies with upstream.

**Comment by nuclearsandwich** [comment]
The original root cause of this issue was that some of the packages in ROS 2 that need urdfdom-headers depended on `urdfdom-headers`, which does not currently resolve to anything, but is the name of an upstream debian package which provides https://github.com/ros/urdfdom_headers. There is a ROS 2 fork of this package at https://github.com/ros2/urdfdom_headers which we're releasing into r2b2 directly.

When first normalizing all keys to `urdfdom_headers` I received the feedback that I should use the dashed name instead in order to seamlessly transition to the upstream package when it becomes available. In order to do this ament_package needed [an update](https://github.com/ros2/robot_model/pull/1#discussion_r122772603) but after doing so there were still issues with the dashed package name conflicting with the underscored CMake project name. While those issues would be resolvable, doing so would require more source changes to our urdfdom_headers fork and possibly its dependents and just renaming the dependency key `urdfdom_headers` with a comment about why and when to change the key name to make use of upstream urdfdom-headers is going to be a less disruptive change than modifying cmake configurations.

**Comment by nuclearsandwich** [comment]
The necessary changes are made, I just need to rename and re-release the package again and these should build... hopefully.

**Comment by nuclearsandwich** [comment]
Resolved with https://github.com/ros2/robot_model/issues/6
