### ISSUE TITLE
ament_python needed to build sourcedeb when used in setup.py

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosdistro-testing#7]
The ament_python package provides a setup.py function for installing scripts into libexec which is imported into setup.py. Packages which use this are failing to build Debian source packages because the build dependencies are not normally installed during the sourcedeb phase, but `setup.py clean` is run which tries to import ament_package and fails with an ImportError ending the build.

```
02:44:43 dpkg-source: info: using options from source/debian/source/options: --auto-commit
02:44:43  fakeroot debian/rules clean
02:44:43 dh clean -v --buildsystem=pybuild --with python3
02:44:43    dh_testdir -O-v -O--buildsystem=pybuild
02:44:43    dh_auto_clean -O-v -O--buildsystem=pybuild
02:44:43 	pybuild --clean -i python{version} -p 3.5 --dir .
02:44:44 I: pybuild base:184: python3.5 setup.py clean 
02:44:44 Traceback (most recent call last):
02:44:44   File "setup.py", line 1, in <module>
02:44:44     from ament_python.script_dir import install_scripts_to_libexec
02:44:44 ImportError: No module named 'ament_python'
02:44:44 E: pybuild pybuild:274: clean: plugin distutils failed with: exit code=1: python3.5 setup.py clean 
02:44:44 dh_auto_clean: pybuild --clean -i python{version} -p 3.5 --dir . returned exit code 13
02:44:44 debian/rules:25: recipe for target 'clean' failed
02:44:44 make: *** [clean] Error 25
02:44:44 dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
02:44:44 debuild: fatal error at line 1376:
02:44:44 dpkg-buildpackage -rfakeroot -d -us -uc -i -I -S failed
02:44:44 gbp:error: 'debuild -i -I -S -us -uc --lintian-opts --suppress-tags newer-standards-version' failed: it exited with 29
```

Example builds

- http://build.ros2.org/view/Rsrc_uX/job/Rsrc_uX__examples_rclpy_minimal_publisher__ubuntu_xenial__source/8/
- http://build.ros2.org/view/Rsrc_uX/job/Rsrc_uX__examples_rclpy_minimal_client__ubuntu_xenial__source/9/
- http://build.ros2.org/view/Rsrc_uX/job/Rsrc_uX__examples_rclpy_minimal_service__ubuntu_xenial__source/8/
- http://build.ros2.org/view/Rsrc_uX/job/Rsrc_uX__examples_rclpy_minimal_subscriber__ubuntu_xenial__source/8/

Possible short- and long-term mitigations I've thought of thus far:

- overriding dh_auto_clean with an `|| true`, I am hesitant to disable it completely because it's also used during the binarydeb phase where there may actually be artifacts worth cleaning up. Whereas if it fails during the sourcedeb phase I'm less concerned as we build in isolated environments that should be clean to begin with.

- somehow making ament-python available at sourcedeb time. Either by installing in the sourcedeb script for everything or trying to detect the package type and making sure it's available, but as we release more python packages we're going to have this problem more generally with anything else that could be imported into setup.py.

- install build-depends during sourcedeb (possibly only for ament_python packages) I haven't looked at the amount of effort this would take or the impact it would have on build times if it weren't scoped to ament_python (and other future build types that require it).

**Comment by clalancette** [comment]
> install build-depends during sourcedeb (possibly only for ament_python packages) I haven't looked at the amount of effort this would take or the impact it would have on build times if it weren't scoped to ament_python (and other future build types that require it).

This seems like the most general solution to me; as you say, we don't know what else could be pulled into setup.py in the future, so this would make it future-proof.

**Comment by wjwwood** [comment]
I don't know what the clean is for, but it probably has a reason to be there. I agree with @clalancette that the last option sounds like the most general solution, but I'm not aware of any repercussions that might incur.

@tfoote would probably be the best person to answer that one off-hand.

**Comment by dirk-thomas** [comment]
The sourcedeb jobs don't use a customized Docker image but only contain
generic packages (single level of Docker). Only the binarydeb jobs generate
a Dockerfile which contains package specific dependencies (two level of
Docker, see
https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm/master/doc/jobs/release_call_graph.png).
Given the time frame adding an additional level of Docker containers for
the sourcedeb jobs is not feasible. While the might be the right long term
approach for this beta a workaround has to be used to get Debian packages
released.

- Dirk

**Comment by nuclearsandwich** [comment]
http://build.ros2.org/view/Rsrc_uX/job/Rsrc_uX__demo_nodes_py__ubuntu_xenial__source/3 is also affected.

**Comment by nuclearsandwich** [comment]
The teleop_twist_keyboard package also uses the ament_python lib and will be affected by this, which is why I haven't released it yet.

**Comment by tfoote** [comment]
So having dependencies in the setup.py is generally frowned upon. Because setup.py is what installs dependencies, if the dependency is missing then you can't even resolve your dependencies. We need to review using that import in our setup.py files as it has consequences beyond the sourcedebs.

In the short term using `|| true` in the sourcedeb should work. The clean option is not strictly necessary since we're building in a clean environment on our buildfarm. But if someone is doing something in a different environment it breaks the debian expectations and could cause improper sourcedeb generation.

**Comment by nuclearsandwich** [comment]
The workaround is sufficient to produce working packages.

**Comment by nuclearsandwich** [comment]
Is https://github.com/ament/ament_python the right place to open an issue discussing the necessity and propriety of using an auxiliary install lib like this?

**Comment by tfoote** [comment]
That's probably a good place to track it.

**Comment by nuclearsandwich** [comment]
Opened an ament_python issue (https://github.com/ament/ament_python/issues/3) to discuss graceful degradation when ament_python is missing.

**Comment by dirk-thomas** [comment]
ament/ament_python#3 has been addressed. Should we close this ticket or do you want to keep it open until `bloom` has been updated accordingly (or want to track that somewhere else - I think it is already covered in an internal Jira ticket)?

**Comment by nuclearsandwich** [comment]
No I think we can close it now. Thanks for the bump.
