### ISSUE TITLE
What kinetic dependencies to use for the ros1_bridge?

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosdistro-testing#8]
At some point today I'll be getting the ROS 1 bridge packaged. My current understanding is that it supports finding and using any messages from ROS 1 available to it at build time.

Soooo what should I add to the packaged version of the bridge?

@clalancette what's needed for the suite of turtlebot2 demos? @mikaelarguedas are there other packages not required for the demo that will support common use cases?

**Comment by clalancette** [comment]
@nuclearsandwich The cartographer demo needs a few of the common messages.  In particular, it wants tf2_msgs, geometry_msgs, nav_msgs, and sensor_msgs.

**Comment by mikaelarguedas** [comment]
I don't think that we need any of the ros1 msg packages except from the bridge. The turtlebot2 demo uses only ros2 messages so the ros1 version of those is not needed. Same for amcl and other demos.

Edit: oh my bad I misread, yeah it depends what we need to visualize on the ROS1 side. so the list provided by @clalancette looks good to me

**Comment by mikaelarguedas** [comment]
Then I don't know exactly what we want to for the bridge in general. Should we provide a bridge with all the common_msgs so that users can easily use it for any non custom messages (even if we dont use them for a specific demo)?

My feeling would be to get `ros-kinetic-std_msgs` `ros-kinetic-common-msgs` `ros-kinetic-std-srvs` and `ros-kinetic-tf2-msgs`
@ros2/team thoughts ?

**Comment by dhood** [comment]
@nuclearsandwich you're correct that it needs to find matches between ROS 1 and ROS 2 messages at build time. While only some are needed for the demo, we should build the bridge with as many common messages as possible so it is useful in other contexts.

These are the packages we install on the buildfarm when the bridge is to be tested:
https://github.com/ros2/ci/blob/9b34a46925ded287e97eb65bc5400904163a2f47/linux_docker_resources/Dockerfile#L86

Some of those are needed for testing the bridge. The ones that bring in the appropriate message packages should be: 
```
ros-kinetic-common-msgs
ros-kinetic-roscpp-tutorials
ros-kinetic-rospy-tutorials 
ros-kinetic-tf2-msgs
```

**Comment by mikaelarguedas** [comment]
agreed, I't just these 2 to @dhood's list:
```
ros-kinetic-std-msgs
ros-kinetic-std-srvs
```

**Comment by dhood** [comment]
they'll get pulled in but yeah. Looking at it again it seems that [catkin and rosmsg are necessary to build the bridge](https://github.com/ros2/ros1_bridge/blob/a8d2822a96b715d11019aedfa38b0011fffe7e13/ros1_bridge/__init__.py#L31), so I was incorrect to assume they were needed for testing. So, it's safest to just pull in all of the dependencies the same as the buildfarm: https://github.com/ros2/ci/blob/9b34a46925ded287e97eb65bc5400904163a2f47/linux_docker_resources/Dockerfile#L86

**Comment by nuclearsandwich** [comment]
> they'll get pulled in but yeah. Looking at it again it seems that catkin and rosmsg are necessary to build the bridge, so I was incorrect to assume they were needed for testing. So, it's safest to just pull in all of the dependencies the same as the buildfarm: https://github.com/ros2/ci/blob/9b34a46925ded287e97eb65bc5400904163a2f47/linux_docker_resources/Dockerfile#L86

Thanks!

**Comment by mikaelarguedas** [comment]
`ros-kinetic-std-srvs` is not pulled in by any of these packages to the best of my knowledge so I think we should add it to the list (if it's not too late, @nuclearsandwich's discretion)

**Comment by nuclearsandwich** [comment]
It'll make it in, I've been working around the ament_python break and haven't packaged this yet.

**Comment by nuclearsandwich** [comment]
Building with the dependencies mentioned here and in the linked Dockerfile, The following error occurs during [build](http://build.ros2.org/job/Rbin_uX64__ros1_bridge__ubuntu_xenial_amd64__binary/4/console#console-section-1).

```
17:37:08 /usr/bin/cmake -E cmake_link_script CMakeFiles/test_ros2_server_cpp.dir/link.txt --verbose=1
17:37:08 /usr/lib/ccache/x86_64-linux-gnu-g++   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2    CMakeFiles/test_ros2_server_cpp.dir/test/test_ros2_server.cpp.o  -o test_ros2_server_cpp /opt/ros/r2b2/lib/libbuiltin_interfaces__rosidl_typesupport_c.so /opt/ros/r2b2/lib/libbuiltin_interfaces__rosidl_typesupport_cpp.so /opt/ros/r2b2/lib/libbuiltin_interfaces__rosidl_typesupport_introspection_c.so /opt/ros/r2b2/lib/libbuiltin_interfaces__rosidl_generator_c.so /opt/ros/r2b2/lib/libbuiltin_interfaces__rosidl_typesupport_introspection_cpp.so /opt/ros/r2b2/lib/librcl_interfaces__rosidl_typesupport_c.so /opt/ros/r2b2/lib/librcl_interfaces__rosidl_typesupport_cpp.so /opt/ros/r2b2/lib/librcl_interfaces__rosidl_typesupport_introspection_c.so /opt/ros/r2b2/lib/librcl_interfaces__rosidl_generator_c.so /opt/ros/r2b2/lib/librcl_interfaces__rosidl_typesupport_introspection_cpp.so /opt/ros/r2b2/lib/librcutils.so /opt/ros/r2b2/lib/librmw.so /opt/ros/r2b2/lib/librosidl_typesupport_introspection_c.so /opt/ros/r2b2/lib/librosidl_typesupport_introspection_cpp.so /opt/ros/r2b2/lib/librmw_fastrtps_cpp.so /opt/ros/r2b2/lib/libfastrtps.so /opt/ros/r2b2/lib/libfastcdr.so -lpthread /opt/ros/r2b2/lib/librosidl_generator_c.so /opt/ros/r2b2/lib/librcl.so /opt/ros/r2b2/lib/librosidl_typesupport_c.so /opt/ros/r2b2/lib/librosidl_typesupport_cpp.so /opt/ros/r2b2/lib/librclcpp.so /opt/ros/kinetic/lib/libroscpp.so /usr/lib/x86_64-linux-gnu/libboost_signals.so /usr/lib/x86_64-linux-gnu/libboost_filesystem.so /opt/ros/kinetic/lib/librosconsole.so /opt/ros/kinetic/lib/librosconsole_log4cxx.so /opt/ros/kinetic/lib/librosconsole_backend_interface.so /usr/lib/x86_64-linux-gnu/liblog4cxx.so /usr/lib/x86_64-linux-gnu/libboost_regex.so /opt/ros/kinetic/lib/libxmlrpcpp.so /opt/ros/kinetic/lib/libroscpp_serialization.so /opt/ros/kinetic/lib/librostime.so /opt/ros/kinetic/lib/libcpp_common.so /usr/lib/x86_64-linux-gnu/libboost_system.so /usr/lib/x86_64-linux-gnu/libboost_thread.so /usr/lib/x86_64-linux-gnu/libboost_chrono.so /usr/lib/x86_64-linux-gnu/libboost_date_time.so /usr/lib/x86_64-linux-gnu/libboost_atomic.so -lpthread /usr/lib/x86_64-linux-gnu/libconsole_bridge.so /opt/ros/r2b2/lib/librosidl_generator_c.so /opt/ros/r2b2/lib/librcl.so /opt/ros/r2b2/lib/librosidl_typesupport_c.so /opt/ros/r2b2/lib/librosidl_typesupport_cpp.so /opt/ros/r2b2/lib/librclcpp.so /opt/ros/kinetic/lib/libroscpp.so /usr/lib/x86_64-linux-gnu/libboost_signals.so /usr/lib/x86_64-linux-gnu/libboost_filesystem.so /opt/ros/kinetic/lib/librosconsole.so /opt/ros/kinetic/lib/librosconsole_log4cxx.so /opt/ros/kinetic/lib/librosconsole_backend_interface.so /usr/lib/x86_64-linux-gnu/liblog4cxx.so /usr/lib/x86_64-linux-gnu/libboost_regex.so /opt/ros/kinetic/lib/libxmlrpcpp.so /opt/ros/kinetic/lib/libroscpp_serialization.so /opt/ros/kinetic/lib/librostime.so /opt/ros/kinetic/lib/libcpp_common.so /usr/lib/x86_64-linux-gnu/libboost_system.so /usr/lib/x86_64-linux-gnu/libboost_thread.so /usr/lib/x86_64-linux-gnu/libboost_chrono.so /usr/lib/x86_64-linux-gnu/libboost_date_time.so /usr/lib/x86_64-linux-gnu/libboost_atomic.so /usr/lib/x86_64-linux-gnu/libconsole_bridge.so -Wl,-rpath,/opt/ros/r2b2/lib:/opt/ros/kinetic/lib: 
17:37:08 CMakeFiles/test_ros2_server_cpp.dir/test/test_ros2_server.cpp.o: In function `rclcpp::service::Service<diagnostic_msgs::srv::SelfTest>::Service(std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::any_service_callback::AnyServiceCallback<diagnostic_msgs::srv::SelfTest>, rcl_service_options_t&)':
17:37:08 /opt/ros/r2b2/include/rclcpp/service.hpp:112: undefined reference to `rosidl_service_type_support_t const* rosidl_typesupport_cpp::get_service_type_support_handle<diagnostic_msgs::srv::SelfTest>()'
17:37:08 collect2: error: ld returned 1 exit status
17:37:08 make[4]: *** [test_ros2_server_cpp] Error 1
17:37:08 CMakeFiles/test_ros2_server_cpp.dir/build.make:162: recipe for target 'test_ros2_server_cpp' failed
```

**Comment by clalancette** [comment]
The symptom of this problem is that something in your link wants diagnostic_msgs, but the diagnostic library (libdiagnostic_msgs__rosidl_typesupport_introspection_c.so) isn't being linked against.  I'm not quite sure why that is; I'm still looking.

**Comment by dhood** [comment]
that would be [this test](https://github.com/ros2/ros1_bridge/blob/c0f46dc9fe138eb02c6193cd972462b5c1daec80/CMakeLists.txt#L168) but I think `ament_target_dependencies` [should take care of adding the link libraries](https://github.com/ament/ament_cmake/blob/3f370ca6c4eed8f2bd3609520fb82012c1db6af0/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake#L55).

Looking for short-term fixes: do we need to build tests for this package?

**Comment by clalancette** [comment]
@dhood I was just wondering the same thing myself :).  @nuclearsandwich It might be worthwhile to disable tests for now and see if that unsticks you; we will, of course, want to find a real solution eventually.

**Comment by nuclearsandwich** [comment]
You can reproduce the build locally following these instructions.

https://gist.github.com/nuclearsandwich/ea731c279e6b5464e836e3db156eb733

> Looking for short-term fixes: do we need to build tests for this package?

We don't _need_ them except to help us identify problems with the generated package. I can override the tests for this package as long as someone who knows how to exercise its full functionality can manually test that the resulting package is valid.

**Comment by nuclearsandwich** [comment]
The linking errors persist but are pretty inconsistent. We'll definitely have to figure out what's actually going on here.

```
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::String_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::BatteryState_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::Int32MultiArray_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::ByteMultiArray_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::MultiDOFJointState_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::MagneticField_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_service_type_support_t const* rosidl_typesupport_cpp::get_service_type_support_handle<diagnostic_msgs::srv::AddDiagnostics>()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::PointStamped_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::JoyFeedback_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<diagnostic_msgs::msg::DiagnosticArray_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::Float64MultiArray_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::UInt64MultiArray_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::UInt16MultiArray_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::FluidPressure_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::QuaternionStamped_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::JoyFeedbackArray_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<diagnostic_msgs::msg::DiagnosticStatus_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::Point32_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::UInt32_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::Illuminance_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::TwistWithCovarianceStamped_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::Int16_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::Vector3Stamped_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::TransformStamped_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::MultiArrayDimension_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::Point_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<sensor_msgs::msg::RegionOfInterest_<std::allocator<void> > >()'
libros1_bridge.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<geometry_msgs::msg::Twist_<std::allocator<void> > >()'
```

**Comment by clalancette** [comment]
All right, I'm going to take another look at this and see what is going on.

**Comment by clalancette** [comment]
For reasons I don't yet understand, what is happening here is that the CMakeLists.txt is failing to find_package() the ROS2 dependencies.  From adding some local debugging, it looks like `ament_index_get_resources(ros2_message_packages "rosidl_interfaces")` is doing the correct thing and finding all of the ROS2 packages in the system.  However, in the loop that follows, it fails to find the packages:

```
foreach(message_package ${ros2_message_packages})
  find_package(${message_package} REQUIRED)
  list(APPEND generated_files "${generated_path}/${message_package}_factories.cpp")
endforeach()
```

Another part I don't understand is that each dependency is marked as REQUIRED, so if there was some problem in find_package(), it should have failed.  I'm still working through this, but any ideas/thoughts are appreciated.

**Comment by mikaelarguedas** [comment]
What does the CMAKE_PREFIX_PATH says at that point? would it be possible
that it's finding the ros1 packages instead of the ros2 ones and thus dont
find the right symbols later on ? (just throwing ideas, I haven't tried any
of it)

On Thu, Jun 29, 2017 at 10:33 AM, Chris Lalancette <notifications@github.com

**Comment by dhood** [comment]
Looking at the output of [this build](http://build.ros2.org/job/Rbin_uX64__ros1_bridge__ubuntu_xenial_amd64__binary/17/console):

```
04:09:47 --   Found visualization_msgs, version 1.12.5
04:09:47 -- Checking for module 'roscpp_tutorials'
04:09:47 --   Found roscpp_tutorials, version 0.7.1
04:09:47 -- Checking for module 'std_srvs'
04:09:47 --   Found std_srvs, version 1.11.2
04:09:47 -- Checking for module 'topic_tools'
04:09:47 --   Found topic_tools, version 1.12.7
04:09:47 -- Found example_interfaces: 0.0.0 (/opt/ros/r2b2/share/example_interfaces/cmake)
```

I wonder if all of the packages it's finding are the ROS 1 ones, and example_interfaces is the only ros2-only one, and you see that it has a different output.

Perhaps the ROS 1 packages are ahead of ROS 2 packages on the path?

**Comment by clalancette** [comment]
Putting `message("${CMAKE_PREFIX_PATH}")` shows an empty string at that point, oddly.  However, I think that both of you are right, and it is re-finding the ROS1 versions of the packages instead of the ROS2 versions.  I'm trying to find ways to make find_package be more verbose about what it does so I can try and manipulate the correct paths.

**Comment by dirk-thomas** [comment]
> Putting message("${CMAKE_PREFIX_PATH}") shows an empty string at that point, oddly.

`CMAKE_PREFIX_PATH` is not a variable in CMake. It is an environment variable which you can get with `$ENV{CMAKE_PREFIX_PATH}`.

**Comment by mikaelarguedas** [comment]
If this is of any help: I think that every output `Checking for module <PACKAGE_NAME>` are the output of pkgconfig (so the ROS1 packages) and all the outputs `Found <PACKAGE_NAME>: x.x.x (absolute path)` are the outputs of `find_package` (so the ROS2 ones if they're the first on the `CMAKE_PREFIX_PATH`)

**Comment by clalancette** [comment]
Ah, thank you.  When I print $ENV{CMAKE_PREFIX_PATH}, it shows:

/opt/ros/kinetic

So yeah, that is definitely the problem.  How we are getting into that situation, I'm not sure yet.

**Comment by dirk-thomas** [comment]
The build sources the file `/opt/ros/r2b2/setup.sh` but that one doesn't set the `CMAKE_PREFIX_PATH`. It only sets `AMENT_PREFIX_PATH`. Therefore the build should do something like this after sourcing:

`export CMAKE_PREFIX_PATH=$AMENT_PREFIX_PATH:$CMAKE_PREFIX_PATH`

**Comment by clalancette** [comment]
Nice!  I was just coming to a similar conclusion, but I didn't know the fix.  Let me try that...

**Comment by clalancette** [comment]
So, if I hard-code the export to:

```
export CMAKE_PREFIX_PATH=/opt/ros/r2b2:/opt/ros/kinetic
```

Things are happy.  For whatever reason, the debian build process really doesn't want me to re-export $ variables.  So we understand the problem, and have a hacky solution; I'll keep plugging on the right way to do this.

**Comment by clalancette** [comment]
Things are looking better now; I don't actually know what happened, but switching back to the $ variables started working again.  I deployed a fix with @nuclearsandwich , it's running on the buildfarm now.  We'll see soon if this fixes it.

**Comment by nuclearsandwich** [comment]
Thanks to Chris's fix the bridge appears happy.
