### ISSUE TITLE
In debian packages, ros2 and launch binaries are located in /usr/bin

### ISSUE THREAD

**Issue by clalancette** [ros2/rosdistro-testing#9]
These should really move to /opt/ros/r2b2/bin to be consistent with everything else.

**Comment by dirk-thomas** [comment]
Hopefully https://github.com/ros2/bloom/commit/31fee87b20f6dfbbcf01aedc7776f8f50c64eab4 will help for this...

**Comment by nuclearsandwich** [comment]
https://github.com/ros2/bloom/commit/f221ee781754f661b03e9baec7cbc019d1cc0ce7 has a fully escaped fix that is building now. I'm going to close this optimistically.

**Comment by dirk-thomas** [comment]
Confirmed to be fixed in the latest Debian package (0.0.0-7).
